// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF25mHy-ZDtP6zpmO6-aHUo6r2-ZZkREs',
    appId: '1:327162963224:android:c27f8517f70215e6a16a6d',
    messagingSenderId: '327162963224',
    projectId: 'flutter-care-168',
    storageBucket: 'flutter-care-168.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4bNgVpxuFklpdYYUMPVDK5xXnbeji5Bg',
    appId: '1:327162963224:ios:e1e9110343c67c99a16a6d',
    messagingSenderId: '327162963224',
    projectId: 'flutter-care-168',
    storageBucket: 'flutter-care-168.appspot.com',
    iosClientId: '327162963224-cig54rcas9pbrppftmsgc6g50365rh68.apps.googleusercontent.com',
    iosBundleId: 'com.chijia.fluttercare168',
  );
}
